# Setup
title:    D.P.O.I.
tagline:  Dise침o y Programaci칩n Orientado a Internet
baseurl:  
github:   https://github.com/FacultadDeIngenieria/dpoi
zip:	    https://github.com/FacultadDeIngenieria/dpoi/zipball/master

# About/contact
author:
name:       Dise침o y Programaci칩n Orientado a Internet
url:
